Add maven package
virtualidentityag/package-deletion pull request #2
Opened 2021-09-07 08:03 UTC by ImpLarsBruemmer

2021-09-07 09:45 UTC, ImpThomasHein requested changes

2021-09-07 09:45 UTC, ImpThomasHein commented on functions.js
> +  } else {
maybe you just do the handling here for docker images, npm packages might also work differently

2021-09-07 09:45 UTC, ImpThomasHein commented on functions.js
> +  } else {
also here, use the specific packageType

2021-09-08 04:21 UTC, ImpLarsBruemmer commented on functions.js
> +  } else {
I added docker and npm handling

2021-09-08 04:22 UTC, ImpLarsBruemmer commented on functions.js
> +  } else {
container is the default one that is why I use the else here

2021-09-09 05:56 UTC, ImpThomasHein approved these changes

2021-09-09 05:56 UTC, merged